name: Build C2EO

on:
  pull_request:
    branches:
      - master

  schedule:
    - cron:  '0 23 * * *'

jobs:
  xcop:
    uses: polystat/c2eo/.github/workflows/xcop.yml@master

  pdd:
    uses: polystat/c2eo/.github/workflows/pdd.yml@master

  cpplint:
    uses: polystat/c2eo/.github/workflows/cpplint.yml@master

  clang-format:
    uses: polystat/c2eo/.github/workflows/clang-format.yml@master

  clang-tidy:
    needs: [cpplint, clang-format]
    uses: polystat/c2eo/.github/workflows/clang-tidy.yml@master

  gcc-c-torture:
    needs: [cpplint, clang-format]
    uses: polystat/c2eo/.github/workflows/gcc-c-torture.yml@master

  c-testcuite:
    needs: [cpplint, clang-format]
    uses: polystat/c2eo/.github/workflows/c-testcuite.yml@master

  test_main:
    needs: [cpplint, clang-format]
    uses: polystat/c2eo/.github/workflows/test_main.yml@master

  csmith:
    needs: [cpplint, clang-format]
    uses: polystat/c2eo/.github/workflows/csmith.yml@master

  unit-tests:
    needs: [cpplint, clang-format]
    uses: polystat/c2eo/.github/workflows/unit-test.yml@master

  codecov:
    needs: [clang-tidy, gcc-c-torture, c-testcuite, test_main, unit-tests]
    uses: polystat/c2eo/.github/workflows/codecov.yml@master
