name: c-testcuite

on:
  workflow_call:

jobs:
  c-testcuite:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: MarkusJx/googletest-installer@v1.1

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: sudo chmod ugo+rwx llvm-clang.tar.gz && tar -xvf llvm-clang.tar.gz -C . > /dev/null

      - name: Download c-testcuite
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "polystat/c2eo"
          tag: "0.1.16"
          fileName: "c-testcuite.tar.gz"

      - name: Unpack c-testcuite
        run: tar -xvf c-testcuite.tar.gz -C . > /dev/null

      - name: Testing
        run: cd ./project/scripts && python3 test.py -p ../../c-testcuite -s testcuite -n -c

      - name: Convert raw code coverage to report
        run: |
          cd ./project/bin/
          llvm-profdata-14 merge -sparse *.profraw -o res.profdata
          llvm-cov-14 show ./c2eo ../src/transpiler/*.cpp -instr-profile=res.profdata > codecov.txt

      - uses: actions/upload-artifact@v3
        with:
          name: testcuite
          path: project/bin/codecov.txt
