name: clang-tidy

on:
  workflow_call:

jobs:
  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: MarkusJx/googletest-installer@v1.1

      - name: Cache LLVM
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: sudo chmod ugo+rwx llvm-clang.tar.gz && tar -xvf llvm-clang.tar.gz -C . > /dev/null
      
      - name: Install clang-tidy
        run: sudo apt install clang-tidy
      
      - name: Clang-tidy
        run: cd ./project/scripts && python3 clang_tidy.py
