name: clang-format

on:
  workflow_call:

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Clang-format
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '14'
          check-path: 'project/src/transpiler'
          fallback-style: 'Google'
