name: cpplint

on:
  workflow_call:

jobs:
  cpplint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: sudo pip install cpplint

      - name: Cpplint
        run: cpplint --filter=-runtime/references,-runtime/string,-build/c++11 project/src/transpiler/**
