name: gcc-c-torture

on:
  workflow_call:

jobs:
  gcc-c-torture:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: MarkusJx/googletest-installer@v1.1

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: sudo chmod ugo+rwx llvm-clang.tar.gz && tar -xvf llvm-clang.tar.gz -C . > /dev/null

      - name: Download gcc-c-torture
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "polystat/c2eo"
          tag: "0.1.16"
          fileName: "gcc.c-torture.tar.gz"

      - name: Unpack gcc-c-torture
        run: tar -xvf gcc.c-torture.tar.gz -C . > /dev/null

      - name: Transpilation
        run: cd ./project/scripts && python3 transpile.py ../../gcc.c-torture -s gcc -n
