name: Statistics

on:
  push

jobs:
  csmith:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: MarkusJx/googletest-installer@v1.1

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: sudo chmod ugo+rwx llvm-clang.tar.gz && tar -xvf llvm-clang.tar.gz -C . > /dev/null

      - name: Install csmith
        run: |
          cd ..
          git clone https://github.com/csmith-project/csmith.git
          cd csmith
          cmake -DCMAKE_INSTALL_PREFIX=csmith .
          make

      - name: Generating tests
        run:  |
          cd ./project/scripts
          python3 csmith.py -h
          python3 csmith.py ../tests/main/csmith -c 200

      - name: Transpilation
        run: |
          cd ./project/scripts
          python3 test.py -h
          python3 test.py -p ../tests/main/csmith -n -i

      - name: Clean test directory
        run: cd ./project/scripts && python3 clean_before_transpilation.py -p ../tests/main/csmith

      - name: Make archive from csmith tests
        run:  tar -cf csmith.tar.gz ./project/tests/main/csmith

      - uses: actions/upload-artifact@v3
        with:
          name: csmith
          path: csmith.tar.gz

  gcc-c-torture:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: MarkusJx/googletest-installer@v1.1

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: sudo chmod ugo+rwx llvm-clang.tar.gz && tar -xvf llvm-clang.tar.gz -C . > /dev/null

      - name: Download gcc-c-torture
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "polystat/c2eo"
          tag: "0.1.16"
          fileName: "gcc.c-torture.tar.gz"

      - name: Unpack gcc-c-torture
        run: tar -xvf gcc.c-torture.tar.gz -C . > /dev/null

      - name: Compilation
        run: |
          cd ./project/scripts
          python3 compile.py -h
          python3 compile.py -p ../../gcc.c-torture -n -i
