name: test_main

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: MarkusJx/googletest-installer@v1.1

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: sudo chmod ugo+rwx llvm-clang.tar.gz && tar -xvf llvm-clang.tar.gz -C . > /dev/null

      - name: Testing
        run: cd ./project/scripts && python3 test.py -s test -c

      - name: Convert raw code coverage to report
        run: |
          cd ./project/bin/
          llvm-profdata-14 merge -sparse *.profraw -o res.profdata
          llvm-cov-14 show ./c2eo ../src/transpiler/*.cpp -instr-profile=res.profdata > codecov.txt

      - uses: actions/upload-artifact@v3
        with:
          name: main
          path: project/bin/codecov.txt
