name: unit_tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: MarkusJx/googletest-installer@v1.1

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: llvm-clang.tar.gz
          key: ${{ runner.os }}-llvm-clang

      - name: Unpack LLVM
        run: sudo chmod ugo+rwx llvm-clang.tar.gz && tar -xvf llvm-clang.tar.gz -C . > /dev/null

      - name: Build c2eo
        run: cd ./project/scripts && python3 build_c2eo.py

      - name: Unit testing
        run: cd ./project/bin/ && ./unit_tests --gtest_filter=*
